[package]
name = "solana-escrow"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.0.2"
thiserror = "1.0.62"
arrayref = "0.3.7"
spl-token = { version = "6.0.0", features = ["no-entrypoint"] }

[lib]
crate-type = ["cdylib", "lib"]
