[package]
name = "escrow-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = { version = "2.0.7" }
solana-program = { version = "2.0.7" }
glob = "0.3.1"
solana-program-test = "2.0.7"
spl-token = { version = "6.0.0",  features = ["no-entrypoint"] }